name: Deploy

# Controls when the action will run.
on:
  push:
    branches: [ dev-server ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
          - uses: actions/checkout@v1
          - name: Push to server
            uses: appleboy/ssh-action@master
            with:
              host: ${{ secrets.SERVER_IP }}
              username: ${{ secrets.SERVER_USERNAME }}
              key: ${{ secrets.SERVER_SSHKEY }}
              script: cd ${{ secrets.PROJECT_PATH }} && git pull